
package fr.afcepf.al23.partesite.taxes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.al23.partesite.taxes.interfaces.Frais;
import fr.afcepf.al23.partesite.taxes.interfaces.ObjectFactory;
import fr.afcepf.al23.partesite.taxes.interfaces.Pays;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceTaxePays", targetNamespace = "http://interfaces.taxes.partesite.al23.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceTaxePays {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.afcepf.al23.partesite.taxes.interfaces.Frais
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFrais", targetNamespace = "http://interfaces.taxes.partesite.al23.afcepf.fr/", className = "fr.afcepf.al23.partesite.taxes.interfaces.GetFrais")
    @ResponseWrapper(localName = "getFraisResponse", targetNamespace = "http://interfaces.taxes.partesite.al23.afcepf.fr/", className = "fr.afcepf.al23.partesite.taxes.interfaces.GetFraisResponse")
    public Frais getFrais(
        @WebParam(name = "arg0", targetNamespace = "")
        Pays arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Pays arg1);

}
