
package fr.afcepf.al23.partesite.taxes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceTaxePaysService", targetNamespace = "http://taxes.partesite.al23.afcepf.fr/", wsdlLocation = "http://localhost:9595/TaxeWebService/ServiceTaxePays?wsdl")
public class ServiceTaxePaysService
    extends Service
{

    private final static URL SERVICETAXEPAYSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICETAXEPAYSSERVICE_EXCEPTION;
    private final static QName SERVICETAXEPAYSSERVICE_QNAME = new QName("http://taxes.partesite.al23.afcepf.fr/", "ServiceTaxePaysService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9595/TaxeWebService/ServiceTaxePays?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICETAXEPAYSSERVICE_WSDL_LOCATION = url;
        SERVICETAXEPAYSSERVICE_EXCEPTION = e;
    }

    public ServiceTaxePaysService() {
        super(__getWsdlLocation(), SERVICETAXEPAYSSERVICE_QNAME);
    }

    public ServiceTaxePaysService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICETAXEPAYSSERVICE_QNAME, features);
    }

    public ServiceTaxePaysService(URL wsdlLocation) {
        super(wsdlLocation, SERVICETAXEPAYSSERVICE_QNAME);
    }

    public ServiceTaxePaysService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICETAXEPAYSSERVICE_QNAME, features);
    }

    public ServiceTaxePaysService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTaxePaysService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceTaxePays
     */
    @WebEndpoint(name = "ServiceTaxePaysPort")
    public IServiceTaxePays getServiceTaxePaysPort() {
        return super.getPort(new QName("http://taxes.partesite.al23.afcepf.fr/", "ServiceTaxePaysPort"), IServiceTaxePays.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceTaxePays
     */
    @WebEndpoint(name = "ServiceTaxePaysPort")
    public IServiceTaxePays getServiceTaxePaysPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://taxes.partesite.al23.afcepf.fr/", "ServiceTaxePaysPort"), IServiceTaxePays.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICETAXEPAYSSERVICE_EXCEPTION!= null) {
            throw SERVICETAXEPAYSSERVICE_EXCEPTION;
        }
        return SERVICETAXEPAYSSERVICE_WSDL_LOCATION;
    }

}
