
package fr.afcepf.al23.servicetaxes_frais.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceTaxes_Frais", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceTaxesFrais {


    /**
     * 
     * @param montantHT
     * @param tauxCommission
     * @param tauxTVA
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "montantTTC", targetNamespace = "")
    @RequestWrapper(localName = "applyTva", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.ApplyTva")
    @ResponseWrapper(localName = "applyTvaResponse", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.ApplyTvaResponse")
    public double applyTva(
        @WebParam(name = "montantHT", targetNamespace = "")
        double montantHT,
        @WebParam(name = "tauxTVA", targetNamespace = "")
        double tauxTVA,
        @WebParam(name = "tauxCommission", targetNamespace = "")
        double tauxCommission);

    /**
     * 
     * @param arg0
     * @return
     *     returns fr.afcepf.al23.servicetaxes_frais.service.Country
     */
    @WebMethod
    @WebResult(name = "country", targetNamespace = "")
    @RequestWrapper(localName = "findCountry", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.FindCountry")
    @ResponseWrapper(localName = "findCountryResponse", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.FindCountryResponse")
    public Country findCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.al23.servicetaxes_frais.service.Country>
     */
    @WebMethod
    @WebResult(name = "coutryList", targetNamespace = "")
    @RequestWrapper(localName = "getAllCountries", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.GetAllCountries")
    @ResponseWrapper(localName = "getAllCountriesResponse", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.GetAllCountriesResponse")
    public List<Country> getAllCountries();

    /**
     * 
     * @param idCountry
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "tauxTva", targetNamespace = "")
    @RequestWrapper(localName = "returnTvaCountry", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.ReturnTvaCountry")
    @ResponseWrapper(localName = "returnTvaCountryResponse", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", className = "fr.afcepf.al23.servicetaxes_frais.service.ReturnTvaCountryResponse")
    public double returnTvaCountry(
        @WebParam(name = "idCountry", targetNamespace = "")
        Integer idCountry);

}
