
package fr.afcepf.al23.servicetaxes_frais.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceTaxes_FraisImplService", targetNamespace = "http://service.servicetaxes_frais.al23.afcepf.fr/", wsdlLocation = "http://localhost:9595/Serviceweb/ServiceTaxes_FraisImpl?wsdl")
public class ServiceTaxesFraisImplService
    extends Service
{

    private final static URL SERVICETAXESFRAISIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICETAXESFRAISIMPLSERVICE_EXCEPTION;
    private final static QName SERVICETAXESFRAISIMPLSERVICE_QNAME = new QName("http://service.servicetaxes_frais.al23.afcepf.fr/", "ServiceTaxes_FraisImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9595/Serviceweb/ServiceTaxes_FraisImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICETAXESFRAISIMPLSERVICE_WSDL_LOCATION = url;
        SERVICETAXESFRAISIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceTaxesFraisImplService() {
        super(__getWsdlLocation(), SERVICETAXESFRAISIMPLSERVICE_QNAME);
    }

    public ServiceTaxesFraisImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICETAXESFRAISIMPLSERVICE_QNAME, features);
    }

    public ServiceTaxesFraisImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICETAXESFRAISIMPLSERVICE_QNAME);
    }

    public ServiceTaxesFraisImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICETAXESFRAISIMPLSERVICE_QNAME, features);
    }

    public ServiceTaxesFraisImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTaxesFraisImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceTaxesFrais
     */
    @WebEndpoint(name = "ServiceTaxes_FraisImplPort")
    public IServiceTaxesFrais getServiceTaxesFraisImplPort() {
        return super.getPort(new QName("http://service.servicetaxes_frais.al23.afcepf.fr/", "ServiceTaxes_FraisImplPort"), IServiceTaxesFrais.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceTaxesFrais
     */
    @WebEndpoint(name = "ServiceTaxes_FraisImplPort")
    public IServiceTaxesFrais getServiceTaxesFraisImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.servicetaxes_frais.al23.afcepf.fr/", "ServiceTaxes_FraisImplPort"), IServiceTaxesFrais.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICETAXESFRAISIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICETAXESFRAISIMPLSERVICE_EXCEPTION;
        }
        return SERVICETAXESFRAISIMPLSERVICE_WSDL_LOCATION;
    }

}
