
package localhost._8080.ode.processes.conversionprocess;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConversionProcessPortType", targetNamespace = "http://localhost:8080/ode/processes/ConversionProcess")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fr.afcepf.al23.conversion.service.ObjectFactory.class,
    fr.afcepf.al23.servicetaxes_frais.service.ObjectFactory.class,
    localhost._8080.ode.processes.conversionprocess.ObjectFactory.class
})
public interface ConversionProcessPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns localhost._8080.ode.processes.conversionprocess.ConversionProcessResponse
     */
    @WebMethod(action = "http://localhost:8080/ode/processes/ConversionProcess/process")
    @WebResult(name = "ConversionProcessResponse", targetNamespace = "http://localhost:8080/ode/processes/ConversionProcess", partName = "payload")
    public ConversionProcessResponse process(
        @WebParam(name = "ConversionProcessRequest", targetNamespace = "http://localhost:8080/ode/processes/ConversionProcess", partName = "payload")
        ConversionProcessRequest payload);

}
