
package process.bpel.al23.afcepf.fr;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessPortType", targetNamespace = "fr.afcepf.al23.bpel.process")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fr.afcepf.al23.conversion.service.ObjectFactory.class,
    fr.afcepf.al23.servicetaxes_frais.service.ObjectFactory.class,
    process.bpel.al23.afcepf.fr.ObjectFactory.class
})
public interface ProcessPortType {


    /**
     * 
     * @param payload
     */
    @WebMethod(action = "fr.afcepf.al23.bpel.process/initiate")
    @Oneway
    public void initiate(
        @WebParam(name = "ProcessRequest", targetNamespace = "fr.afcepf.al23.bpel.process", partName = "payload")
        ProcessRequest payload);

}
