
package process.bpel.al23.afcepf.fr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Process", targetNamespace = "fr.afcepf.al23.bpel.process", wsdlLocation = "http://localhost:8282/ode/processes/Process?wsdl")
public class Process
    extends Service
{

    private final static URL PROCESS_WSDL_LOCATION;
    private final static WebServiceException PROCESS_EXCEPTION;
    private final static QName PROCESS_QNAME = new QName("fr.afcepf.al23.bpel.process", "Process");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/ode/processes/Process?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESS_WSDL_LOCATION = url;
        PROCESS_EXCEPTION = e;
    }

    public Process() {
        super(__getWsdlLocation(), PROCESS_QNAME);
    }

    public Process(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESS_QNAME, features);
    }

    public Process(URL wsdlLocation) {
        super(wsdlLocation, PROCESS_QNAME);
    }

    public Process(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESS_QNAME, features);
    }

    public Process(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Process(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessPortType
     */
    @WebEndpoint(name = "ProcessPort")
    public ProcessPortType getProcessPort() {
        return super.getPort(new QName("fr.afcepf.al23.bpel.process", "ProcessPort"), ProcessPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessPortType
     */
    @WebEndpoint(name = "ProcessPort")
    public ProcessPortType getProcessPort(WebServiceFeature... features) {
        return super.getPort(new QName("fr.afcepf.al23.bpel.process", "ProcessPort"), ProcessPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESS_EXCEPTION!= null) {
            throw PROCESS_EXCEPTION;
        }
        return PROCESS_WSDL_LOCATION;
    }

}
